### ISSUE TITLE
DevContainer の構成を CI でチェックする

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/lean-by-example#480]
ChatGPT はこういっていて，ちょっと修正すれば使えそう

ただし，`validate` というサブコマンドは存在しないっぽい

```yml
name: Validate Devcontainer

on: [push, pull_request]

jobs:
  validate-devcontainer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install devcontainer-cli
      run: npm install -g @devcontainers/cli

    - name: Validate devcontainer.json
      run: devcontainer validate

```
